### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.linear_model.base'

### ISSUE THREAD

**Issue by dashikapv** [NishantGautam023/Final-Year-Project#1]
Traceback (most recent call last):
  File "C:\Users\Dashika\Downloads\Final-Year-Project-master\Final-Year-Project-master\server\server.py", line 32, in <module>
    util.load_saved_artifacts()
  File "C:\Users\Dashika\Downloads\Final-Year-Project-master\Final-Year-Project-master\server\util.py", line 37, in load_saved_artifacts
    __model = _pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.linear_model.base'

**Comment by NiisG** [comment]
`pip install -U scikit-learn scipy matplotlib`
   Or
Try reinstalling the jupyter 
`conda install -c anaconda ipython`
